###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "Usa3",
  "password": "pasa",
  "email": "mail@gmail.com",
  "kd": 0,
  "adr": 0,
  "ranking": 0,
  "teamId": 0,
  "persmissionLevel": 0
}

<> 2025-03-19T203816.201.json

###
PUT http://localhost:8080/api/user
Content-Type: application/json

{
  "id": 1,
  "username": "Usa2",
  "password": "pasa",
  "email": "mail@gmail.com",
  "kd": 1.2,
  "adr": 80,
  "ranking": 1000,
  "teamId": 0,
  "persmissionLevel": 0
}

<> 2025-03-19T204834.200.json

### all
GET http://localhost:8080/api/user

<> 2025-03-19T205019.200.json

### username = usa
GET http://localhost:8080/api/user?username=usa2

### id = 2
GET http://localhost:8080/api/user?id=3



###
POST http://localhost:8080/api/team?
    teamId={{$random.integer(100)}}&
    name={{$random.alphanumeric(8)}}
    Content-Type: application/x-www-form-urlencoded



<> 2025-03-19T203815.500.json
<> 2025-03-19T203803.500.json
<> 2025-03-19T203802.500.json
<> 2025-03-19T203339.400.json

###
GET http://localhost:8080/api/user